# Generated by Django 6.0.7 on 2026-07-31 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Chat Histories'},
        ),
        migrations.AlterModelOptions(
            name='documentsmetadata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Documents Metadata'},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='intent',
            field=models.CharField(default='RAG', max_length=50),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentsmetadata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
